services:
  backend:
    build: ./backend/tiny-link
    container_name: TinyLink_backend
    working_dir: /app/tiny-link
    env_file:
      - db/.env
    volumes:
      - ./scripts:/app/scripts
      - .db:/app/db
      - ./backend/tiny-link:/app/tiny-link
    stdin_open: true
    tty: true
    networks:
      - shared_network
    ports:
      - 8080:8080
    depends_on:
      mariadb:
        condition: service_healthy

  mariadb:
    image: mariadb:latest
    container_name: TinyLink_mariadb
    command: '--default-authentication-plugin=mysql_native_password'
    env_file:
      - db/.env
    environment:
      MARIADB_DATABASE: ${DATABASE_NAME}
      MARIADB_USER: ${DATABASE_USER}
      MARIADB_PASSWORD: ${DATABASE_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 60s
    ports:
      - ${DATABASE_PORT}:3306
    restart: ${RESTART_POLICY}
    networks:
      - shared_network

networks:
  shared_network:
    driver: bridge