volumes:
  tinylink:
 
services:
  mariadb:
    image: ${DATABASE_IMAGE_TAG}
    container_name: ${DATABASE_CONTAINER_NAME}
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - tinylink:/var/lib/mysql
    environment:
      MARIADB_DATABASE: ${DATABASE_NAME}
      MARIADB_USER: ${DATABASE_USER}
      MARIADB_PASSWORD: ${DATABASE_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 60s
    ports:
      - ${DATABASE_PORT}:3306
    restart: ${RESTART_POLICY}
    networks:
      - shared_network
  volumes:
    tinylink:

networks:
  shared_network:
    driver: bridge